version: '2'
services:

    main:
        build: .
        image: puffinrocks/flux-fetch
        ports:
            - 3000
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        networks:
            - front
            - back
            - default
networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
